server:
  port: 8081

spring:
  application:
    name: iam-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/iam_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
          jws-algorithm: HS256

app:
  jwt:
    secret: this-is-a-very-long-dev-secret-key-change-in-prod-12345

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
